QUERY_DIVIDAS_DISPUTAS

WITH DIVIDAS AS (
SELECT
	RAWTOHEX(DEBT.IDT_DEBT) AS DIVIDA_ID,
	DEBT.NUM_DEBT_AMOUNT AS VALOR_DIVIDA,
	DEBT.NUM_DEBITED_AMOUNT AS VALOR_RECUPERADO,
	(DEBT.NUM_DEBT_AMOUNT - DEBT.NUM_DEBITED_AMOUNT) AS VALOR_PENDENTE,
	DEBT.DAT_CREATION AS DT_CRIACAO_DIVIDA,
	DEBT.DAT_EXPIRES AS DT_EXPIRACAO,
	DEBT.DAT_UPDATE AS DT_ULTIMA_ATUALIZACAO,
	CASE
		DEBT.IND_STATUS
			WHEN 'PD' THEN 'PAGA'
			WHEN 'AC' THEN 'ATIVA'
			WHEN 'C1' THEN 'CANCELANDO'
			WHEN 'C2' THEN 'CANCELADO'
			WHEN 'PE' THEN 'PENDENTE'
		ELSE DEBT.IND_STATUS
	END STATUS_DIVIDA,
	DR.NAM_CHANGE_AGENT AS RESPONSAVEL_DIVIDA,
	DR.DES_TYPE AS TIPO_DIVIDA,
	DR.DES_REASON AS MOTIVO
FROM CASHIN_DEBT_ADM.DEBT DEBT
LEFT JOIN CASHIN_DEBT_ADM.DEBT_REFERRER DR ON DEBT.IDT_DEBT = DR.IDT_DEBT
WHERE 1=1
AND
    DEBT.DAT_CREATION >= TRUNC(SYSDATE - 2)
AND DEBT.DAT_CREATION <= TRUNC(SYSDATE)
), FONTE_PAGAMENTO AS (
SELECT
	DISTINCT RAWTOHEX(DS.IDT_DEBT) AS DIVIDA_IDF,
	CASE
		LISTAGG(DS.IND_TYPE) WITHIN GROUP (ORDER BY DS.IDT_DEBT, DS.IND_TYPE) OVER (PARTITION BY DS.IDT_DEBT)
			WHEN 'DA' THEN 'Conta Digital'
			WHEN 'DS' THEN 'Agenda de Débitos'
			WHEN 'AB' THEN 'Disponível da Adquirência'
			WHEN 'DADS' THEN 'Agenda de Débitos, Conta Digital'
			WHEN 'ABDADS' THEN 'Agenda de Débitos, Conta Digital, Disponível da Adquirência'
			WHEN 'ABDA' THEN 'Conta Digital, Disponível da Adquirência'
			WHEN 'ABDS' THEN 'Agenda de Débitos, Disponível da Adquirência'
		ELSE LISTAGG(DS.IND_TYPE) WITHIN GROUP (ORDER BY DS.IDT_DEBT, DS.IND_TYPE) OVER (PARTITION BY DS.IDT_DEBT)
	END ORIGEM_PAGAMENTO
FROM CASHIN_DEBT_ADM.DEBIT_SOURCE DS
WHERE 1=1
AND DS.DAT_START >= TRUNC(SYSDATE - 2)
AND DS.DAT_START <= TRUNC(SYSDATE)
), MIN_IDT_STATUS_48 AS (
	SELECT
		MIN(TSH.IDT_TRANSACTION_STATUS_HISTORY)ID,
		TSH.IDT_TRANSACTION
	FROM SAFEPAY_ADM.TRANSACTION_STATUS_HISTORY TSH
	WHERE 1=1
	AND TSH.IDT_TRANSACTION_STATUS = '48'
	AND TSH.DAT_CREATION >= TRUNC(SYSDATE - 2)
    AND TSH.DAT_CREATION <= TRUNC(SYSDATE)
	GROUP BY TSH.IDT_TRANSACTION
)
SELECT
	D.IDT_DISPUTE AS DISPUTA_ID,
	D.IDT_TRANSACTION AS TRANSACAO_ID,
	T.COD_SAFEPAY_TRANSACTION AS COD_TRANSACAO,
	D.IDT_SAFEPAY_CREDITOR AS VENDEDOR_ID,
	D.IDT_SAFEPAY_DEBTOR AS COMPRADOR_ID,
	D.IND_WINNER AS VENCEDOR_DISPUTA,
	D.IND_STATUS AS STATUS_DISPUTA,
	D.IND_SOLUTION AS DESEJO_COMPRADOR,
	D.IND_REASON AS MOTIVO_COMPRADOR,
	D.IND_CLOSED_BY AS RESPONSAVEL_ENCERRAMENTO,
	D.IND_REFUND_TYPE AS TIPO_REEMBOLSO,
	TS.DES_INTERNAL_STATUS AS STATUS_TRANSACAO,
	TY.DES_TRANSACTION_TYPE AS TIPO_TRANSACAO,
	PM.DES_PAYMENT_METHOD AS METODO_TRANSACAO,
	EVENT.IND_CASH_IN,
	EVENT.IND_SUCCESS,
	T.DAT_START_ESCROW AS DT_PAGAMENTO,
	CEIL(T.NUM_MILLISEC_ESCROW/86400000) AS ESCROW_DIAS,
	D.DAT_START AS DT_DISPUTA,
	D.DAT_START_MODERATION AS DT_MODERACAO,
	TSH.DAT_CREATION AS DT_SEM_SOLUCAO,
	D.DAT_CLOSED AS DT_ENCERRAMENTO,
	(T.NUM_TRANSACTION_ORIGINAL_VALUE - T.NUM_CREDITOR_TAX_VALUE) AS VALOR_LIQUIDO,
	DIV.DIVIDA_ID,
	DIV.VALOR_DIVIDA,
	DIV.VALOR_RECUPERADO,
	DIV.VALOR_PENDENTE,
	DIV.DT_CRIACAO_DIVIDA,
	DIV.DT_EXPIRACAO,
	DIV.DT_ULTIMA_ATUALIZACAO,
    FP.DIVIDA_IDF,
	FP.ORIGEM_PAGAMENTO,
	DIV.STATUS_DIVIDA,
	DIV.RESPONSAVEL_DIVIDA,
	DIV.TIPO_DIVIDA,
	DIV.MOTIVO
	
FROM SAFEPAY_ADM.DISPUTE D
LEFT JOIN SAFEPAY_ADM.TRANSACTION T ON D.IDT_TRANSACTION = T.IDT_TRANSACTION
LEFT JOIN SAFEPAY_ADM.DEBT_CASH_IN_EVENT EVENT ON T.COD_SAFEPAY_TRANSACTION = EVENT.COD_TRANSACTION
LEFT JOIN DIVIDAS DIV ON EVENT.COD_DEBT = DIV.DIVIDA_ID
LEFT JOIN FONTE_PAGAMENTO FP ON DIV.DIVIDA_ID = FP.DIVIDA_IDF
LEFT JOIN MIN_IDT_STATUS_48 S48 ON D.IDT_TRANSACTION = S48.IDT_TRANSACTION
LEFT JOIN SAFEPAY_ADM.TRANSACTION_STATUS_HISTORY TSH ON S48.ID = TSH.IDT_TRANSACTION_STATUS_HISTORY
LEFT JOIN SAFEPAY_ADM.TRANSACTION_STATUS TS ON T.IDT_TRANSACTION_STATUS = TS.IDT_TRANSACTION_STATUS
LEFT JOIN SAFEPAY_ADM.TRANSACTION_TYPE TY ON T.IDT_TRANSACTION_TYPE = TY.IDT_TRANSACTION_TYPE
LEFT JOIN SAFEPAY_ADM.PAYMENT_METHOD PM ON T.IDT_MAIN_PAYMENT_METHOD = PM.IDT_PAYMENT_METHOD
WHERE 1=1
AND  D.DAT_START >= TRUNC(SYSDATE - 2)
AND  D.DAT_START <= TRUNC(SYSDATE)
OR   D.DAT_CLOSED >= TRUNC(SYSDATE - 2)
AND  D.DAT_CLOSED <= TRUNC(SYSDATE)
AND EVENT.IND_ACTION = 'CR'
;