TRANSACOES CREDITO E DEBITO

SELECT
	T.IDT_SAFEPAY_CREDITOR AS ID_VENDEDOR,
	T.IDT_TRANSACTION AS ID_TRANSACAO,
	T.COD_SAFEPAY_TRANSACTION AS COD_TRANSACAO,
	DECODE(T.IDT_MAIN_PAYMENT_METHOD, '8','DEBITO','3','CREDITO') AS TIPO_PGTO,
	T.NUM_TRANSACTION_TOTAL_VALUE AS VALOR_TRANSACAO
FROM TRANSACTION T
WHERE 1 = 1
AND T.IDT_MAIN_PAYMENT_METHOD IN(3,8)
AND EXISTS (
			SELECT *
			FROM ULTIMAS_TRANSACOES_DEB_CRE UT 
			WHERE T.IDT_SAFEPAY_CREDITOR = UT.IDT_SAFEPAY_USER
			)
AND T.IDT_TRANSACTION IN (
							SELECT MAX(T1.IDT_TRANSACTION)
							FROM TRANSACTION T1
							WHERE T.IDT_SAFEPAY_CREDITOR = T1.IDT_SAFEPAY_CREDITOR
							AND T.IDT_MAIN_PAYMENT_METHOD IN (3,8)
							)
;