SELECT
	TO_CHAR(T.DAT_CREATION,'DD/MM/YYYY') AS DATA_TRANSACAO,
	COALESCE(DC.NUM_DEBIT_CARD_DISPLAY, CC.NUM_CREDIT_CARD_DISPLAY) AS BIN_PORTADOR,
	COALESCE(CC.COD_AUTHORIZATION, DC.COD_AUTHORIZATION) AS AUTORIZACAO,
	TO_CHAR(T.DATA_CONTESTACAO,'DD/MM/YYYY') AS DATA_CONTESTACAO,
	CONCAT(P.NAM_PERSON, CONCAT(' ',I.NAM_LAST)) AS NOME_COMPLETO,
	COALESCE(PF.NUM_CPF, PJ.NUM_CNPJ) AS DOCUMENTO,
	T.IDT_SAFEPAY_CREDITOR AS ID_VENDEDOR,
	T.TIPO_DE_CONTA,
	DECODE(T.TIPO_DE_CONTA,'C','Comprador','P','Pessoal','V','Vendedor','E','Empresarial','R','Comprador','S','Vendedor') as TIPO_DE_CONTA,
	COALESCE(CC.COD_NSU_OPERATOR, DC.COD_NSU_OPERATOR) AS NSU,
	COALESCE(DC.COD_INTEGRATOR, CC.COD_INTEGRATOR, CC.COD_TID_OPERATOR) AS TID,
	T.IDT_TRANSACTION AS ID_TRANSACAO,
	T.COD_SAFEPAY_TRANSACTION AS COD_TRANSACAO,
	T.STATUS_TRANSACAO,
	T.STATUS_CONTESTACAO,
	T.VALOR_TRANSACAO,
	DECODE(T.IDT_TRANSACTION_TYPE,'3','ADICAO DE FUNDOS') AS TIPO_TRANSACAO,
	DECODE(T.IDT_MAIN_PAYMENT_METHOD,'3','CREDITO','8','DEBITO') AS METODO_PGTO
FROM
(
SELECT
	T.DAT_CREATION,
	C.DAT_CREATION AS DATA_CONTESTACAO,
	SU.IND_USER_TYPE AS TIPO_DE_CONTA,
	T.IDT_SAFEPAY_CREDITOR,
	T.IDT_TRANSACTION,
	T.COD_SAFEPAY_TRANSACTION,
	T.IDT_TRANSACTION_TYPE,
	T.IDT_MAIN_PAYMENT_METHOD,
	(SELECT TS.DES_INTERNAL_STATUS FROM SAFEPAY_ADM.TRANSACTION_STATUS TS WHERE T.IDT_TRANSACTION_STATUS = TS.IDT_TRANSACTION_STATUS) AS STATUS_TRANSACAO,
	T.NUM_TRANSACTION_TOTAL_VALUE AS VALOR_TRANSACAO,
	T.IDT_TRANSACTION_STATUS,
	CASE C.IND_STATUS
			WHEN 	'AD'	THEN	'Negado automaticamente'
			WHEN 	'AL'	THEN	'Analisado'
			WHEN 	'AN'	THEN	'Em análise'
			WHEN	'AP'	THEN	'Aprovado'
			WHEN	'AW'	THEN	'Negado automaticamente - Aguardando notificação'
			WHEN	'CC'	THEN	'Encerrada / Chargeback debitado'
			WHEN	'DE'	THEN	'Negado'
			WHEN	'ER'	THEN	'Erro de Processamento'
			WHEN	'EX'	THEN	'Expirado'
			WHEN	'NB'	THEN	'Não Bloqueado'
			WHEN	'NN'	THEN	'Não Notificado'
			WHEN	'RL'	THEN	'Reporte liberado'
			WHEN	'RR'	THEN	'Reavaliação de reporte'
			WHEN	'TC'	THEN	'Encerrada / Transação estornada'
			WHEN	'WN'	THEN	'Aguardando notificação'
			WHEN	'WR'	THEN	'Aguardando comprovante'
	END 
	STATUS_CONTESTACAO
FROM SAFEPAY_ADM.TRANSACTION T
LEFT JOIN SAFEPAY_ADM.CONTESTATION C ON T.IDT_TRANSACTION = C.IDT_TRANSACTION
LEFT JOIN SAFEPAY_ADM.SAFEPAY_USER SU ON T.IDT_SAFEPAY_CREDITOR = SU.IDT_SAFEPAY_USER
WHERE 1 = 1 
AND T.IDT_TRANSACTION_TYPE = 3
AND T.IDT_MAIN_PAYMENT_METHOD IN(3,8)
--AND T.DAT_CREATION >= DATE'2018-05-16'
AND T.DAT_CREATION BETWEEN DATE'2018-05-16' AND DATE'2018-12-31'
)T
LEFT JOIN (	SELECT * FROM SAFEPAY_ADM.TRANSACTION_PAYMENT_ATTEMPT TPA 
			WHERE 1 = 1
			AND TPA.IDT_PAYMENT_METHOD IN (3,8)
			AND EXISTS (	SELECT *
							FROM SAFEPAY_ADM.TRANSACTION_PAYMENT TP 
							WHERE TPA.IDT_PAYMENT_ATTEMPT = TP.IDT_PAYMENT_ATTEMPT
						)
			) TPA ON T.IDT_TRANSACTION = TPA.IDT_TRANSACTION
LEFT JOIN SAFEPAY_ADM.CREDIT_CARD CC ON TPA.IDT_PAYMENT_ATTEMPT = CC.IDT_PAYMENT_ATTEMPT
LEFT JOIN SAFEPAY_ADM.DEBIT_CARD DC ON TPA.IDT_PAYMENT_ATTEMPT = DC.IDT_PAYMENT_ATTEMPT
LEFT JOIN SAFEPAY_ADM.SAFEUSER_REGISTERED SR ON T.IDT_SAFEPAY_CREDITOR = SR.IDT_SAFEPAY_USER
LEFT JOIN UOLBR.PERSON P ON SR.IDT_PERSON = P.IDT_PERSON
LEFT JOIN UOLBR.CADASTRO_PESSOA_FISICA PF ON SR.IDT_PERSON = PF.IDT_PERSON
LEFT JOIN UOLBR.CADASTRO_PESSOA_JURIDICA PJ ON SR.IDT_PERSON = PJ.IDT_PERSON
LEFT JOIN UOLBR.INDIVIDUAL I ON SR.IDT_PERSON = I.IDT_PERSON
;